### ISSUE TITLE
How to get the trapezohedron

### ISSUE THREAD

**Issue by PaulieMoly** [flammpfeil/SlashBlade#92]
Hi i have a question as to how to get the traphezohedron i saw others saying that u could get it through lighting the stand whil its ignited with slashbladecrystal but it doesnt work.

**Comment by flammpfeil** [comment]
bladestand(on blade) > tinysoul (burn) > proudsoul(get crystal) > tinysoul (burn) > crystal (get trapezohedron)

**Comment by flammpfeil** [comment]
Should this happen?
https://youtu.be/Lg9i1Inyncw

**Comment by PaulieMoly** [comment]
does this work on 1.7.10 because im using that version and that texture of
proudsoul and tinysoul isnt like mine, also when i try to get trapezohedron
in creative it has like a long name to it, flammpfeil/slashblade... pls
update 1.7.10 because nothing happens when i left click the blade with
crystal after ignited with tiny soul.

**Comment by PaulieMoly** [comment]
Can you please update 1.7.10 to the latest version with the cool item with
flames, I tried the 1.12 r28 but it crashed for me, the message it gave me
was "The game crashed whilst rendering item
Error: java.lang.NoSuchMethodError:
net.minecraft.client.renderer.BufferBuilder.putBulkData(Ljava/nio/ByteBuffer;)V"
So i downloaded 1.11.2 version and tried that out, everything you stated
works there but not in 1.7.10 please do update it because i did a custom
modpack in that version and most of the mods there can't be brought to the
present version, thanks for your time.

**Comment by PaulieMoly** [comment]
Also 1.7.10 i cant make legendary bewitch (yellow color) the texture may
not work because i think it requires spectral arrow but please do update it
so that crafting bamboo light sword can be crafted, thank you.
